# Generated by Django 3.1.1 on 2022-04-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforusform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforusform',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workforusform',
            name='kindofwork',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workforusform',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
