# Generated by Django 3.1.1 on 2022-04-15 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='userform',
        ),
    ]
